package com.minecraftstory.story;

public enum StoryFlag {
    INTRO_LIGHT_SEEN,
    INTRO_MEMORY_MISSING,
    INTRO_LIGHT_DENIED,
    HEARD_THE_VOICE,
    CAEL_RECOGNIZED_MARK,
    ELIAS_FOUND,
    MERCY_PATH,
    KNOWLEDGE_PATH,
    HOLLOW_KNIGHT_SEEN,
    CRYSTAL_SEALED,
    CRYSTAL_TOUCHED,
    CRYSTAL_DESTROY_ATTEMPTED,
    CHAPTER_1_COMPLETE,
    CHAPTER_2_UNLOCKED
}
