package com.minecraftstory.story;

public enum StoryFlag {
    PLAYER_PLACED,
    INTRO_STARTED,
    INTRO_LIGHT_SEEN,
    INTRO_MEMORY_MISSING,
    INTRO_LIGHT_DENIED,
    HEARD_THE_VOICE,
    CAEL_RECOGNIZED_MARK,
    ELIAS_FOUND,
    MERCY_PATH,
    KNOWLEDGE_PATH,
    HOLLOW_KNIGHT_SEEN,
    CRYSTAL_SEALED,
    CRYSTAL_TOUCHED,
    CRYSTAL_DESTROY_ATTEMPTED,
    CHAPTER_1_COMPLETE,
    CHAPTER_2_UNLOCKED,
    CHAPTER_2_STARTED,
    CHAPTER_2_STAR_FOUND,
    CHAPTER_2_ASHES_PATH,
    CHAPTER_2_MAP_TRUTH,
    CHAPTER_2_COMPLETE,
    POST_CREDITS_SCENE_SEEN
}
